[tool.poetry]
name = "svc-juniper-lib"
version = "0.1.0"
description = "Juniper automation utilities for SVC"
authors = ["Lee Sharping <lsharping@equinix.com>"]

packages = [
    { include = "svc_juniper_lib", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"
junos-eznc = ">=2.7.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"