[tool.poetry]
name = "svc-synchronize-lib"
version = "0.1.0"
description = "Synchronize logic for SVC"
authors = ["Lee Sharping <lsharping@equinix.com>"]

packages = [
    { include = "svc_synchronize_lib", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.8"
svc-netbox-lib = { path = "../svc_netbox_lib", develop = true }
svc-juniper-lib = { path = "../svc_juniper_lib", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
