site_name: SVC Python Libraries
repo_url: https://github.com/equinix-svc/svc-libraries

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.annotate

nav:
  - Home: index.md
  - API Reference:
      - Juniper: juniper.md
      - Netbox: netbox.md
      - Synchronize: synchronize.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - packages/svc_juniper_lib/src
            - packages/svc_netbox_lib/src
            - packages/svc_synchronize_lib/src
          options:
            docstring_style: google
            show_source: true
            heading_level: 2
            merge_init_into_class: true
            show_root_heading: true
